src/SmartAdmin.WebUI/Models/Security/Profile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SideXC.WebUI.Models.Security
{
    public class Profile
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "Please type a valid description.")]
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}

src/SmartAdmin.WebUI/Controllers/Security/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SideXC.WebUI.Data;
using SideXC.WebUI.Models.Security;

namespace SideXC.WebUI.Controllers.Security
{
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProfilesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Profiles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Profiles.ToListAsync());
        }

        // GET: Profiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Active")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                profile.Active = true;
                _context.Add(profile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles.FindAsync(id);
            if (profile == null)
            {
                return NotFound();
            }
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,Active")] Profile profile)
        {
            if (id != profile.Id)
            {
                return NotFound();
            }

            if (ProfileExists(profile.Description))
            {
                ModelState.AddModelError("Err", "The Description already exists in the database.");
                return View(profile);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    ModelState.AddModelError("Err", e.Message);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        private bool ProfileExists(string description)
        {
            return _context.Profiles.Any(e => e.Description == description);
        }
    }
}

src/SmartAdmin.WebUI/Views/Profiles/Create.cshtml
@model SideXC.WebUI.Models.Security.Profile

@{
    ViewData["Title"] = "Profile - New Item";
}


<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Security</li>
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Profiles")">Profile</a></li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">            
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        New Item
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label asp-for="Description" class="control-label font-weight-bold"></label>
                                    <input asp-for="Description" class="form-control form-control-sm" required autocomplete="off"/>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>

                            </div>

                            <button class="btn btn-primary" type="submit"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</main>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SmartAdmin.WebUI/Views/Profiles/Edit.cshtml
@model SideXC.WebUI.Models.Security.Profile

@{
    ViewData["Title"] = "Create";
}


<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Security</li>
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Profiles")">Profile</a></li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">            
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Edit Item
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                        <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-row">
                                <div class="col-md-12 mb-3">
                                    <input type="hidden" asp-for="Id" />
                                    <label asp-for="Description" class="control-label font-weight-bold"></label>
                                    <input asp-for="Description" class="form-control form-control-sm" required />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" asp-for="Active">
                                        <label class="custom-control-label" for="Active">Status</label>
                                    </div>
                                </div>
                            </div>

                            <button class="btn btn-primary" type="submit"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</main>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SmartAdmin.WebUI/Views/Profiles/Index.cshtml
@model IEnumerable<SideXC.WebUI.Models.Security.Profile>

@{
    ViewData["Title"] = "Index";
}

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Security</li>
        <li class="breadcrumb-item active">Profile</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Information
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">

                        <!-- datatable start -->
                        <table id="tableReport" >
                            <thead >
                                <tr>
                                    <th class="text-center">
                                        <a class="btn btn-sm btn-outline-light btn-pills" title="Create New Item" asp-action="Create"><span class="fa fa-plus"></span> </a>
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th class="text-center">
                                        @Html.DisplayNameFor(model => model.Active)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td id="tdBtn" class="text-center">
                                        <a class="btn btn-sm btn-outline-warning btn-pills" title="Edit item @item.Description" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-edit"></span></a>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Active)
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>

                        <!-- datatable end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

@section ScriptsBlock {
    <script src="~/js/utilities/common.js"></script>
    <script src="~/js/datagrid/datatables/datatables.bundle.js"></script>
    <script src="~/js/datagrid/datatables/datatables.export.js"></script>

    <script>
        $(document).ready(function () {
            _ConvertToDatatableWithButtons("tableReport", "ProfilesFile", 0);
        });
    </script>
}