src/SmartAdmin.WebUI/Controllers/Inventory/WarehousesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SideXC.WebUI.Data;
using SideXC.WebUI.Models.Inventory;

namespace SideXC.WebUI.Controllers.Inventory
{
    public class WarehousesController : BaseController
    {
        private readonly ApplicationDbContext _context;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        public WarehousesController(ApplicationDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Index view
        /// </summary>
        /// <returns></returns>
        [Authorization]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Warehouses.ToListAsync());
        }
        /// <summary>
        /// Create view
        /// </summary>
        /// <returns></returns>
        [Authorization]
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Create post
        /// </summary>
        /// <param name="warehouse"></param>
        /// <returns></returns>
        [Authorization]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Active,Created,Modified")] Warehouse warehouse)
        {
            if (WarehouseExists(warehouse.Description))
            {
                ModelState.AddModelError("Error", "Ya existe un almacen con esa descripción.");
            }
            if (ModelState.IsValid)
            {
                warehouse.Active = true;
                warehouse.Created = DateTime.Now;
                warehouse.CreatedBy = UserLogged;
                warehouse.Modified = DateTime.Now;
                warehouse.ModifiedBy = UserLogged;
                _context.Add(warehouse);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(warehouse);
        }
        /// <summary>
        /// Edit view
        /// </summary>
        [Authorization]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) { return NotFound(); }
            var warehouse = await _context.Warehouses.FindAsync(id);
            if (warehouse == null) { return NotFound(); }
            return View(warehouse);
        }
        /// <summary>
        /// Edit post
        /// </summary>
        /// <param name="id"></param>
        /// <param name="warehouse"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [Authorization]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,Active,Created,Modified")] Warehouse warehouse, IFormCollection collection)
        {
            var description = collection["hddDescription"].ToString();
            if (id != warehouse.Id) { return NotFound(); }
            if (warehouse.Description != description)
            {
                if (WarehouseExists(warehouse.Description))
                {
                    ModelState.AddModelError("Error", "Ya existe un almacen con esa descripción.");
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    warehouse.Modified = DateTime.Now;
                    warehouse.ModifiedBy = UserLogged;
                    _context.Update(warehouse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WarehouseExists(warehouse.Description)) { return NotFound(); }
                    else { throw; }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(warehouse);
        }
        /// <summary>
        /// Valida nuevo item
        /// </summary>
        /// <param name="description"></param>
        /// <returns></returns>
        private bool WarehouseExists(string description)
        {
            return _context.Warehouses.Any(e => e.Description == description);
        }
    }
}

src/SmartAdmin.WebUI/Views/Warehouses/Create.cshtml
@model SideXC.WebUI.Models.Inventory.Warehouse

@{
    ViewData["Title"] = "Warehouse - New Item";
}


<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Inventory</li>
        <li class="breadcrumb-item">Catalogs</li>
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Warehouses")">Warehouse</a></li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        New Item
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <form asp-action="Create">
                            <div asp-validation-summary="All" class="bg-danger pt-2 pb-2 text-white mb-4"></div>
                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label asp-for="Description" class="control-label font-weight-bold"></label>
                                    <input asp-for="Description" class="form-control form-control-sm" required autocomplete="off" />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>

                            </div>

                            <button class="btn btn-primary" type="submit"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SmartAdmin.WebUI/Views/Warehouses/Edit.cshtml
@model SideXC.WebUI.Models.Inventory.Warehouse

@{
    ViewData["Title"] = "Edit";
}


<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Inventory</li>
        <li class="breadcrumb-item">Catalogs</li>
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Warehouses")">Warehouse</a></li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Edit Item
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <form asp-action="Edit">
                            <div asp-validation-summary="All" class="bg-danger pt-2 pb-2 text-white mb-4"></div>
                            <div class="form-row">
                                <div class="col-md-12 mb-3">
                                    <input type="hidden" asp-for="Id" />
                                    <input type="hidden" id="hddDescription" name="hddDescription" value="@Model.Description" />
                                    <label asp-for="Description" class="control-label font-weight-bold"></label>
                                    <input asp-for="Description" class="form-control form-control-sm" required autocomplete="off" />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" asp-for="Active">
                                        <label class="custom-control-label" for="Active">Status</label>
                                    </div>
                                </div>
                            </div>

                            <button class="btn btn-primary" type="submit"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/SmartAdmin.WebUI/Views/Warehouses/Index.cshtml
@model IEnumerable<SideXC.WebUI.Models.Inventory.Warehouse>

@{
    ViewData["Title"] = "Inventory Catalogs - Warehouse";
}

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Inventory</li>
        <li class="breadcrumb-item">Catalogs</li>
        <li class="breadcrumb-item active">Warehouse</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Information
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">

                        <!-- datatable start -->
                        <table id="tableReport">
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        <a class="btn btn-sm btn-outline-light btn-pills" title="Create New Item" asp-action="Create"><span class="fa fa-plus"></span> </a>
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th class="text-center">
                                        @Html.DisplayNameFor(model => model.Active)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Created)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modified)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td id="tdBtn" class="text-center">
                                            <a class="btn btn-sm btn-outline-warning btn-pills" title="Edit item @item.Description" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-edit"></span></a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.Active)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Created)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Modified)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                        <!-- datatable end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

@section ScriptsBlock {
    <script src="~/js/utilities/common.js"></script>
    <script src="~/js/datagrid/datatables/datatables.bundle.js"></script>
    <script src="~/js/datagrid/datatables/datatables.export.js"></script>

    <script>
        $(document).ready(function () {
            _ConvertToDatatableWithButtons("tableReport", "WarehouseFile", 4);
        });
    </script>
}