src/SmartAdmin.WebUI/Models/Inventory/Hallway.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using SideXC.WebUI.Models.Security;
using SideXC.WebUI.Data;

namespace SideXC.WebUI.Models.Inventory
{
    public class Hallway
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100, ErrorMessage = "Please type a valid description.")]
        [MaxLength(100, ErrorMessage = "Maximum lenth is 100 characters for this field.")]
        [Required(ErrorMessage = "Required.")]
        public string Description { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public bool Active { get; set; }
        public DateTime Created { get; set; }
        public virtual ApplicationUser CreatedBy { get; set; }
        public DateTime Modified { get; set; }
        public virtual ApplicationUser ModifiedBy { get; set; }
    }
}

src/SmartAdmin.WebUI/Controllers/Inventory/HallwaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SideXC.WebUI.Data;
using SideXC.WebUI.Models.Inventory;

namespace SideXC.WebUI.Controllers.Inventory
{
    public class HallwaysController : BaseController
    {
        private readonly ApplicationDbContext _context;
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="context"></param>
        public HallwaysController(ApplicationDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Index view
        /// </summary>
        /// <returns></returns>
        [Authorization]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hallways.Include(i => i.Warehouse).ToListAsync());
        }
        /// <summary>
        /// Create view
        /// </summary>
        /// <returns></returns>
        [Authorization]
        public IActionResult Create()
        {
            var listWarehouse = _context.Warehouses.Where(c => c.Active == true).ToList();
            ViewBag.Warehouses = new SelectList(listWarehouse, "Id", "Description");
            return View();
        }
        /// <summary>
        /// Create post
        /// </summary>
        /// <param name="hallway"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [Authorization]
        [HttpPost]
        public async Task<IActionResult> Create(Hallway hallway, IFormCollection collection)
        {
            var warehouseId = int.Parse(collection["Warehouse"].ToString());
            var warehouse = _context.Warehouses.FirstOrDefault(w => w.Id == warehouseId);
            hallway.Warehouse = warehouse;

            if (HallwayExists(hallway.Description, hallway.Warehouse))
            {
                ModelState.AddModelError("Error", "Ya existe un pasillo con esa descripción.");
            }
            if (ModelState.IsValid)
            {
                hallway.Active = true;
                hallway.Created = DateTime.Now;
                hallway.CreatedBy = UserLogged;
                hallway.Modified = DateTime.Now;
                hallway.ModifiedBy = UserLogged;
                _context.Add(hallway);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var listWarehouse = _context.Warehouses.Where(c => c.Active == true).ToList();
            ViewBag.Warehouses = new SelectList(listWarehouse, "Id", "Description");
            return View(hallway);
        }
        /// <summary>
        /// Edit view
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorization]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var listWarehouse = _context.Warehouses.Where(c => c.Active == true).ToList();
            ViewBag.Warehouses = new SelectList(listWarehouse, "Id", "Description");
            var hallway = await _context.Hallways.FindAsync(id);
            if (hallway == null)
            {
                return NotFound();
            }
            return View(hallway);
        }
        /// <summary>
        /// Edit post
        /// </summary>
        /// <param name="id"></param>
        /// <param name="hallway"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [Authorization]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Hallway hallway, IFormCollection collection)
        {
            var description = collection["hddDescription"].ToString();
            var warehouseId = int.Parse(collection["Warehouse"].ToString());
            var warehouse = _context.Warehouses.FirstOrDefault(w => w.Id == warehouseId);
            hallway.Warehouse = warehouse;

            if (id != hallway.Id) { return NotFound(); }
            if (hallway.Description != description)
            {
                if (HallwayExists(hallway.Description, hallway.Warehouse))
                {
                    ModelState.AddModelError("Error", "Ya existe un pasillo con esa descripción.");
                }
            }
            if (ModelState.IsValid)
            {
                try
                {
                    hallway.Modified = DateTime.Now;
                    hallway.ModifiedBy = UserLogged;
                    _context.Update(hallway);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HallwayExists(hallway.Description, hallway.Warehouse)) { return NotFound(); }
                    else { throw; }
                }
                return RedirectToAction(nameof(Index));
            }
            var listWarehouse = _context.Warehouses.Where(c => c.Active == true).ToList();
            ViewBag.Warehouses = new SelectList(listWarehouse, "Id", "Description");
            return View(hallway);
        }
        /// <summary>
        /// Valida si existe el nuevo item
        /// </summary>
        /// <param name="description"></param>
        /// <param name="warehouse"></param>
        /// <returns></returns>
        private bool HallwayExists(string description, Warehouse warehouse)
        {
            return _context.Hallways.Any(e => e.Description == description && e.Warehouse.Id == warehouse.Id);
        }
    }
}

src/SmartAdmin.WebUI/Views/Hallways/Create.cshtml
@model SideXC.WebUI.Models.Inventory.Hallway


@{
    ViewData["Title"] = "Hallway - New Item";
}

@Html.AntiForgeryToken()

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Inventory</li>
        <li class="breadcrumb-item">Catalogs</li>
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Hallways")">Hallway</a></li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        New Item
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <form asp-action="Create">
                            <div asp-validation-summary="All" class="bg-danger pt-2 pb-2 text-white mb-4"></div>
                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <label asp-for="Description" class="control-label font-weight-bold"></label>
                                    <input asp-for="Description" class="form-control form-control-sm" required autocomplete="off" />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="Warehouse" class="control-label">Warehouse </label>
                                    <select asp-for="Warehouse" class="form-control form-control-sm" asp-items="@(new SelectList(ViewBag.Warehouses,"Value", "Text"))">
                                        <option value="">-Please select one-</option>
                                    </select>
                                </div>
                            </div>

                            <button class="btn btn-primary" type="button" onclick="Save()"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                            <button id="btnSave" class="btn btn-primary d-none" type="submit"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/utilities/common.js"></script>

    <script>

        function Save() {
            var warehouse = $('#Warehouse').val();
            if (warehouse == "") {
                _AlertSideXC("Favor de seleccionar un Almacen.", "danger");
                return;
            }
            $('#btnSave').click();
        }
    </script>
}

src/SmartAdmin.WebUI/Views/Hallways/Edit.cshtml
@model SideXC.WebUI.Models.Inventory.Hallway

@{
    ViewData["Title"] = "Hallway - Edit Item";
}

@Html.AntiForgeryToken()

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Inventory</li>
        <li class="breadcrumb-item">Catalogs</li>
        <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Hallways")">Hallway</a></li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Edit Item
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">
                        <form asp-action="Edit">
                            <div asp-validation-summary="All" class="bg-danger pt-2 pb-2 text-white mb-4"></div>
                            <div class="form-row">
                                <div class="col-md-6 mb-3">
                                    <input type="hidden" asp-for="Id" />
                                    <input type="hidden" id="hddDescription" name="hddDescription" value="@Model.Description" />
                                    <label asp-for="Description" class="control-label font-weight-bold"></label>
                                    <input asp-for="Description" class="form-control form-control-sm" required autocomplete="off" />
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <label for="Warehouse" class="control-label">Profile </label>
                                    <select asp-for="Warehouse" class="form-control form-control-sm" asp-items="@(new SelectList(ViewBag.Warehouses,"Value", "Text"))">
                                        <option value="">-Please select one-</option>
                                    </select>
                                </div>
                                <div class="col-md-12 mb-3">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" asp-for="Active">
                                        <label class="custom-control-label" for="Active">Status</label>
                                    </div>
                                </div>
                            </div>

                            <button class="btn btn-primary" type="button" onclick="Save()"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                            <button id="btnSave" class="btn btn-primary d-none" type="submit"><span class="fa fa-save"></span>&nbsp; Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    $(document).ready(function () {
        $('#Warehouse').val(@Model.Warehouse.Id);
    });

    function Save() {
        var warehouse = $('#Warehouse').val();
        if (warehouse == "") {
            _AlertSideXC("Favor de seleccionar un Almacen.", "danger");
            return;
        }
        $('#btnSave').click();
    }
</script>

}

src/SmartAdmin.WebUI/Views/Hallways/Index.cshtml
@model IEnumerable<SideXC.WebUI.Models.Inventory.Hallway>
@{
    ViewData["Title"] = "Inventory Catalogs - Hallway";
}

<main id="js-page-content" role="main" class="page-content">
    <ol class="breadcrumb page-breadcrumb">
        <li class="breadcrumb-item"><a href="/#">Home</a></li>
        <li class="breadcrumb-item">Inventory</li>
        <li class="breadcrumb-item">Catalogs</li>
        <li class="breadcrumb-item active">Hallway</li>
        <li class="position-absolute pos-top pos-right d-none d-sm-block"><span class="js-get-date"></span></li>
    </ol>
    <div class="row">
        <div class="col-xl-12">
            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2>
                        Information
                    </h2>
                    <div class="panel-toolbar">
                        <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                        <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    </div>
                </div>
                <div class="panel-container show">
                    <div class="panel-content">

                        <!-- datatable start -->
                        <table id="tableReport">
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        <a class="btn btn-sm btn-outline-light btn-pills" title="Create New Item" asp-action="Create"><span class="fa fa-plus"></span> </a>
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th>@Html.DisplayNameFor(model => model.Warehouse)</th>
                                    <th class="text-center">
                                        @Html.DisplayNameFor(model => model.Active)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Created)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Modified)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td id="tdBtn" class="text-center">
                                        <a class="btn btn-sm btn-outline-warning btn-pills" title="Edit item @item.Description" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-edit"></span></a>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Warehouse.Description)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Active)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Created)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Modified)
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>

                        <!-- datatable end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

@section ScriptsBlock {
    <script src="~/js/utilities/common.js"></script>
    <script src="~/js/datagrid/datatables/datatables.bundle.js"></script>
    <script src="~/js/datagrid/datatables/datatables.export.js"></script>

    <script>
        $(document).ready(function () {
            _ConvertToDatatableWithButtons("tableReport", "EmployeeTypeFile", 5);
        });
    </script>
}